#!/usr/bin/env python3
"""Get all packages belonging to a team

Copyright 2017 Canonical Ltd.
Joshua Powers <josh.powers@canonical.com>
"""
import argparse
import json
from urllib.request import urlopen


def get_packages_from_mapping(team):
    """Return package team mapping.

    @return: list of packages belonging to a team.
    """
    team_url = ("http://people.canonical.com/~ubuntu-archive/"
                "package-team-mapping.json")
    with urlopen(team_url) as url:
        data = json.loads(url.read().decode())

    try:
        return data[team]
    except KeyError:
        return []

def main(team):
    """Return packages belonging to a team."""
    packages = get_packages_from_mapping(team)
    for package in packages:
        print(package, end=' ')

if __name__ == '__main__':
    PARSER = argparse.ArgumentParser()
    PARSER.add_argument('team', help='Team packages to get')
    ARGS = PARSER.parse_args()

main(ARGS.team)
